{
 "title": "Energy Production & Cost Summary",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "tz", "label": "Timezone", "query": "Europe/Berlin" }
  ]
 },
 "panels": [
  {
   "title": "Self consumption",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Autonomy",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Solar to home",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Solar to Grid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Grid to home",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0)"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  }
 ]
}